version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: 12345678
      DATABASE_NAME: Student
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: Student
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    # volumes:
    #   - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
# # crates new network
# # networks:
# #   fastapi-app-network:
# #     driver: bridge

  # mysql:
  #   image: mysql
  #   restart: on-failure
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "12345678"
  #     MYSQL_DATABASE: Student
  #     MYSQL_PASSWORD: "12345678"
  #   ports:
  #     - "3306:3306"
  
  #   networks:
  #     - fastapi-app-network