version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    depends_on:
      - mysql
    networks:
      - fastapi-app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: Student
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fastapi-app-network

volumes:
  mysql_data:

# crates new network
networks:
  fastapi-app-network:
    driver: bridge