version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: Student
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    networks:
      - fastapi-app
 
networks: 
  fastapi-app:
    name: fastapi-app
    driver: bridge 